#!/bin/bash
# Installs the latest version of Python from source code.
# Install required tools:
sudo yum install -y git gcc make tmux htop

# tmux and htop are only used if you want to do this manually and watch the CPUs
# sit at 100% usage while compiling

# Switch to your home directory
cd $HOME

# Download Python and switch to the directory
git clone https://github.com/python/cpython
cd cpython

# List the 'tags' for different versions in the git repo
# git tag

# Switch to v3.10.4 tag (most recent stable build when creating this script)
git checkout v3.10.4

# Run the build configuration script
./configure

# Compile it using the Makefile generated by the build script
make -j 8  # This tells make to use 8 CPUs, watch them in htop

# List the contents of the directory once you've compiled it
ls -al

# Run your new Python executable
echo "Run your new Python executable with the command:"
echo "./python"
echo "Don't forget to update your PATH if you want to run it by typing 'python' without the ./"
