version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - "8000:8001"
    environment:
      CONTAINER_ID: MY FIRST CONTAINER

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend